-- =============================================================================
-- ADV055 — H2 schema for the `repository` module test slice.
--
-- Mirrors the Liquibase changesets that this module's tests actually touch:
--   002-schema.xml  -> counterparties, instruments, trades
--   003-jsonb.xml   -> instruments.metadata (the H2 branch: JSON, not JSONB)
--   009-envers.xml  -> revinfo, revinfo_seq, trades_aud (@Audited on Trade means
--                      every insert writes a revision row)
--
-- The other entities in `domain` are never queried here, so their tables are
-- deliberately absent — ddl-auto is `none`, so nothing validates them.
-- =============================================================================

DROP TABLE IF EXISTS trades_aud;
DROP TABLE IF EXISTS trades;
DROP TABLE IF EXISTS instruments;
DROP TABLE IF EXISTS counterparties;
DROP TABLE IF EXISTS revinfo;
DROP SEQUENCE IF EXISTS revinfo_seq;

CREATE TABLE counterparties (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    lei_code   VARCHAR(20)  NOT NULL UNIQUE,
    region     VARCHAR(10)  NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE instruments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol      VARCHAR(20)  NOT NULL UNIQUE,
    name        VARCHAR(200) NOT NULL,
    asset_class VARCHAR(20)  NOT NULL,
    currency    VARCHAR(3)   NOT NULL,
    metadata    JSON DEFAULT '{}' NOT NULL,
    isin        VARCHAR(12) UNIQUE
);

CREATE TABLE trades (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_ref       VARCHAR(30) NOT NULL UNIQUE,
    instrument_id   BIGINT      NOT NULL REFERENCES instruments (id),
    counterparty_id BIGINT      NOT NULL REFERENCES counterparties (id),
    asset_class     VARCHAR(20) NOT NULL,
    side            VARCHAR(4)  NOT NULL,
    quantity        NUMERIC(18, 4) NOT NULL,
    price           NUMERIC(18, 4) NOT NULL,
    trade_date      DATE        NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    deleted_at      TIMESTAMP,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at     TIMESTAMP
);

CREATE INDEX idx_trades_trade_date ON trades (trade_date);
CREATE INDEX idx_trades_status ON trades (status);

CREATE TABLE revinfo (
    rev      INTEGER PRIMARY KEY,
    revtstmp BIGINT
);

CREATE SEQUENCE revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE trades_aud (
    rev             INTEGER NOT NULL REFERENCES revinfo (rev),
    id              BIGINT  NOT NULL,
    revtype         SMALLINT,
    trade_ref       VARCHAR(30),
    instrument_id   BIGINT,
    counterparty_id BIGINT,
    asset_class     VARCHAR(20),
    side            VARCHAR(4),
    quantity        NUMERIC(18, 4),
    price           NUMERIC(18, 4),
    trade_date      DATE,
    status          VARCHAR(20),
    deleted_at      TIMESTAMP,
    created_at      TIMESTAMP,
    modified_at     TIMESTAMP,
    PRIMARY KEY (rev, id)
);
